#nullable enable
using System.Xml;
using Monocle;

namespace FortRise;

/// <summary>
/// A sprite entry used for adding textures and running it by frames.
/// </summary>
public interface ISpriteEntry
{
    /// <summary>
    /// A sprite identity for SpriteData.
    /// </summary>
    public string ID { get; init; }
    /// <summary>
    /// An autogenerated xml data of this sprite.
    /// </summary>
    public XmlElement Xml { get; }
}

/// <summary>
/// A concreted sprite entry used for adding textures and running it by frames.
/// </summary>
public interface ISpriteEntry<T> : ISpriteEntry
{
    /// <summary>
    /// A concreted <see cref="Monocle.Sprite{T}"/> component.
    /// </summary>
    public Sprite<T>? Sprite { get; }
    /// <summary>
    /// A concreted <see cref="SpriteConfiguration{T}"/> .
    /// </summary>
    public SpriteConfiguration<T> Configuration { get; init; }
}