name = "menuatlas"
output_path = "../Atlas"
output_type = "Json"
allow_normal_output = false
template_path = ["template.xml"]
folders = [
    "mmg",
    "icon"
]

[image_options]
output_extension = "Png"
max_size = 4096
show_extension = false

[features]
nine_patch = false

